### ISSUE TITLE
Proxy recovery

### ISSUE THREAD

**Issue by AhmedAlK** [mehrdadjg/Scalability-Dolphins#16]
The proxy is not stateless as it stores data in the form of sockets. For this reason, we cannot assume that it will not fail.

As a result, we have a requirement to ensure that the proxy can recover. This recovery process is helped by the low amount of data that the proxy needs to hold.

For recovery, we are to implement:
1. The data held by the proxy needs to be minimized to facilitate quick and lossless recovery.
2. Clients and replicas detect proxy disconnect, and attempt to reconnect until aborted or successful.
3. reconnect should use a special "reconnect" signal to allow clients to continue their session without needing to log back in or open the file a second time.
4. on reconnect, all clients and replicas should ensure that they are caught up as some of them may reconnect after the session has been reestablished and more updates are made.

**Comment by AhmedAlK** [comment]
The server may store some session information (eg. opened files and clients working on them) _with low overhead_ which will facilitate transparent recovery. This was pointed out during the presentation prep on Nov 15th.

**Comment by AhmedAlK** [comment]
After discussion, we determined that a reconnect signal is unnecessary, as would proxy storage of session information. The remaining points have been addressed in #26

**Comment by bwstaple** [comment]
Client still doesn't handle proxy death, shame on Mehrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrdad
